name = "Hugo Minimal Test"
description = "Module for Hugo Minimal Test Theme Component"

[module]
  [module.hugoVersion]
    min = "0.81.0"
    extended = false

  [[module.imports]]
     path = "github.com/danielfdickinson/hugo-debug-tables"

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca"
  copyright = "© 2021 Daniel F. Dickinson"
